site_name: 波场中文文档
site_url: https://tronprotocol.github.io/documentation-zh/introduction/
repo_url: https://github.com/tronprotocol/documentation-zh

nav:
    - 首页: index.md
    - 简介:
        - 项目仓库: introduction/index.md
        - 波场共识: introduction/dpos.md
        - 波场概览: introduction/overview.md
    - API 接口:
        - HTTP 接口: api/http.md
        - RPC 接口: api/rpc.md
    - 机制与算法:
        - 超级代表与委员会: mechanism-algorithm/sr.md
        - TRC-10: mechanism-algorithm/trc10.md
        - 账户模型: mechanism-algorithm/account.md
        - 资源模型: mechanism-algorithm/resource.md
        - 去中心化交易所: mechanism-algorithm/dex.md
        - 多重签名: mechanism-algorithm/multi-signatures.md
        - 匿名交易: mechanism-algorithm/shielded-transaction.md
        - 系统合约: mechanism-algorithm/system-contracts.md
    - 架构介绍:
        - 网络: architecture/network.md
        - 数据库: architecture/database.md
        - 插件: architecture/plugin.md
    - 智能合约文档:
        - 虚拟机: contracts/tvm.md
        - 编译器: contracts/compiler.md
        - 合约: contracts/contract.md
        - TRC-20: contracts/trc20.md
    - 开发者文档:
        - 官方节点: developers/official-public-nodes.md
        - 部署: developers/deployment.md
        - 在 IDEA 中启动节点: developers/run-in-idea.md
        - 资源: developers/resources.md
        - 参与开发: developers/contribution.md
        - 激励政策: developers/incentives.md
        - Java-Tron: developers/java-tron.md
        - TIPs: developers/tips.md
        - 高级配置项: developers/advanced-configuration.md
    - 客户端:
        - 命令行钱包: clients/wallet-cli.md
        - clients/tron-grid.md
    - 常见问题: faq/index.md
    - 术语表: glossary.md

theme: readthedocs
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - footnotes
    - codehilite
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.tilde
    - pymdownx.tasklist
    - pymdownx.superfences
